### PR TITLE
Add Vulkan backend

### PR DESCRIPTION
**Pull request by Ldash4**

### CODE REVIEW

**Comment by ThisDevDane** [comment]
Could you add a build target to the Makefile as well?

**Comment by ThisDevDane** [comment]
Could you also mark things as `@(private="package")` that isn't meant to be used otherwise

**Comment by Ldash4** [comment]
There's no Vulkan/SDL example if that's what you mean

**Comment by ThisDevDane** [comment]
> There's no Vulkan/SDL example if that's what you mean

Right, my bad

**Comment by Ldash4** [comment]
Uh I totally forgot that I need to inline the spirv shaders, so don't merge just yet

**Comment by Ldash4** [comment]
Alright, hopefully I haven't missed anything else obvious

**Comment by Ldash4** [comment]
> Alright, hopefully I haven't missed anything else obvious

I realize that I assume that you're rendering to SRGB. I'll probably fix this

**Pull request merged**
